export const SET_DATABASES = 'SET_DATABASES'
export const SET_DATABASE  = 'SET_DATABASE'
export const ADD_DATABASE = 'ADD_DATABASE'
export const REMOVE_DATABASE = 'REMOVE_DATABASE'

export const SET_QUESTIONS = 'SET_QUESTIONS'
export const ADD_QUESTION = 'ADD_QUESTION'
export const REMOVE_QUESTION = 'REMOVE_QUESTION'

export const SET_STUDENTS = 'SET_STUDENTS'

export const EXAM_SET_DATABASE = 'EXAM_SET_DATABASE'
export const EXAM_GET_DATABASE = 'EXAM_GET_DATABASE'
